a=str(input())
chat={"one":"hello","two":"What food you want","three":"how tables you need","four":"Any extra toppings","five":"any other menu","six":"that all"}
print(chat["one"])
print("Welcome to the hotel ")
b=str(input())
print(chat["two"])
c=str(input())
print(chat["three"])
d=str(input())
print(chat["four"])
e=str(input())
print(chat["five"])
f=str(input())
print(chat["six"])
print("The details are :")
print("FOOD ORDERED",c)
print("TABLE COUNT",d)
print("EXTRA TOPPINGS",e)
print("OTHER MENU",f)
print("******************")